### ISSUE TITLE
Cannot apply patches with non-ascii characters inside

### ISSUE THREAD

**Issue by miquelraynal** [getpatchwork/pwclient#1]
Hello,

I am using patchwork/pwclient for quite some time now to manage my linux-mtd patches.

I recently got into troubles because of one contributor having a non-ascii character in its name (I suppose this is the root cause). Here is the trace:

```
$ git pwc -rN100
pw_filter=
git-pwc: Patchwork cache too cold, retrieving patch list for linux-mtd...pwclient command: pwclient list -p linux-mtd -N 100 -s New 
 done
Traceback (most recent call last):
  File "/home/mraynal/.local/bin/pwclient", line 10, in <module>
    sys.exit(main())
  File "/home/mraynal/.local/lib/python2.7/site-packages/pwclient/shell.py", line 757, in main
    print(s)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0142' in position 7360: ordinal not in range(128)
```

This is happening with the latest pwclient from Git:
`698fa7f Fix return code when getting patch information fails`

Here is the patch I tried to apply:
[mtd-onenand-Add-support-for-8Gb-datasize-onenand.patch.txt](https://github.com/getpatchwork/pwclient/files/3201263/mtd-onenand-Add-support-for-8Gb-datasize-onenand.patch.txt)

Right now I use the following hack to avoid being bothered, but there are probably many other places where this can happen and a cleaner solution would be welcome!
```
diff --git a/pwclient/shell.py b/pwclient/shell.py
index 43c7a37..30826fa 100644
--- a/pwclient/shell.py
+++ b/pwclient/shell.py
@@ -754,7 +754,7 @@ installed locales.
             for patch_id in non_empty(h, patch_ids):
                 s = rpc.patch_get_mbox(patch_id)
                 if len(s) > 0:
-                    print(s)
+                    print(s.encode('utf-8', errors='ignore'))
 
     elif action == 'info':
         for patch_id in non_empty(h, patch_ids):
```

**Comment by miquelraynal** [comment]
Indeed this is a Python 2.7 issue only and migrating to Python 3 is probably the best way to go. However, migrating the script to Python 3 will imply a few changes in the code. I tried to run it with Python 3 already and the script crashes, I did not investigate further.
