### ISSUE TITLE
Crash when migrating old config

### ISSUE THREAD

**Issue by ShaunTheQuietGamer** [getpatchwork/pwclient#13]
I'm getting an error when migrating an old config, version  2.0.0, installed through `pip`
```/home/shaun/.pwclientrc is in the old format. Migrating it...Traceback (most recent call last):
  File "/usr/bin/pwclient", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/pwclient/shell.py", line 45, in main
    utils.migrate_old_config_file(CONFIG_FILE, config)
  File "/usr/lib/python3.10/site-packages/pwclient/utils.py", line 17, in migrate_old_config_file
    old_project = config.get('base', 'project')
  File "/usr/lib/python3.10/configparser.py", line 782, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.10/configparser.py", line 1153, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'base'```

**Comment by ShaunTheQuietGamer** [comment]
Actually, my fault, i didn't read all the comments in the pwclientrc i downloaded from patchworks and i wasn't able to decipher that error message right away, i didn't uncomment 
```[options]
default=linux-wireless```
