### ISSUE TITLE
'check-get' command is broken in 2.2.0

### ISSUE THREAD

**Issue by robherring** [getpatchwork/pwclient#18]
Running check-get command results in a splat:

$ pwclient check-get 1643273
Traceback (most recent call last):
  File "/home/rob/.local/bin/pwclient", line 10, in <module>
    sys.exit(main())
  File "/home/rob/.local/lib/python3.10/site-packages/pwclient/shell.py", line 245, in main
    checks.action_get(api, patch_id, format_str)
  File "/home/rob/.local/lib/python3.10/site-packages/pwclient/checks.py", line 42, in action_get
    checks_list = api.patch_check_get(patch_id)
AttributeError: 'XMLRPC' object has no attribute 'patch_check_get'

**Comment by stephenfin** [comment]
Thanks. This will be fixed in 2.2.1.
