### ISSUE TITLE
The delegate option gives an error 'Must be User instance'

### ISSUE THREAD

**Issue by dlezcano** [getpatchwork/pwclient#5]
Hi,
when I run this command:

    pwclient list -p linux-pm -s New -N 3 -d "daniel.lezcano@linaro.org"

I'm getting this output but unable to parse the problem.

```
Patches delegated to Daniel Lezcano <daniel.lezcano@linaro.org>:
Traceback (most recent call last):
  File "/usr/local/bin/pwclient", line 11, in <module>
    sys.exit(main())
  File "/home/dlezcano/.local/lib/python2.7/site-packages/pwclient/shell.py", line 129, in main
    patches.action_list(rpc, filt, submitter_str, delegate_str, format_str)
  File "/home/dlezcano/.local/lib/python2.7/site-packages/pwclient/patches.py", line 144, in action_list
    patches = rpc.patch_list(f.d)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close
    raise Fault(**self._stack[0])
xmlrpclib.Fault: <Fault 1: u'<class \'ValueError\'>:Cannot query "Daniel Lezcano <daniel.lezcano@linaro.org>": Must be "User" instance.'>
```

**Comment by stephenfin** [comment]
This looks like a server-side error. What instance are you using? The server logs will identify the issue, assuming it hasn't been fixed in a newer version already.

**Comment by stephenfin** [comment]
No updates. There's nothing I can really do here without server logs.
