### ISSUE TITLE
pwclient crash when migrating old config

### ISSUE THREAD

**Issue by montjoie** [getpatchwork/pwclient#9]
```
/home/compile/.pwclientrc is in the old format. Migrating it...Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.7/pwclient", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.7/site-packages/pwclient/shell.py", line 45, in main
    utils.migrate_old_config_file(CONFIG_FILE, config)
  File "/usr/lib/python3.7/site-packages/pwclient/utils.py", line 41, in migrate_old_config_file
    new_config.write(fd)
  File "/usr/lib/python3.7/configparser.py", line 918, in write
    self._sections[section].items(), d)
  File "/usr/lib/python3.7/configparser.py", line 922, in _write_section
    fp.write("[{}]\n".format(section_name))
TypeError: a bytes-like object is required, not 'str'
```

This is my old config:

```
[base]                                                                                              
url: https://patchwork.kernel.org/xmlrpc/
project: linux-arm-kernel
```

**Comment by stephenfin** [comment]
A silly mistake. Thanks for highlighting it. This is fixed now and has been released as 1.3.1
